### PR TITLE
MNT: Re-rendered with conda-smithy 2.4.5

### PR DESCRIPTION
**Pull request by bollwyvl**
Rerendering, hoping for linux builds :)

### CODE REVIEW

**Comment by synapticarbors** [comment]
Not sure why there were only osx builds for py3.6. Otherwise it looks like the rest are there. I'm happy to merge this once it completes. Just ping me again when it does if I don't get to it quickly.

**Comment by bollwyvl** [comment]
Right, should have specified linux-64 py36! Merge away, if all good! Thanks!

**Comment by synapticarbors** [comment]
hmm, all of the CircleCI builds failed on merge:

https://circleci.com/gh/conda-forge/wsaccel-feedstock/9

**Comment by bollwyvl** [comment]
Aw, shucks, i thought that was behind us. I had run into that before:
https://github.com/conda-forge/statsd-feedstock/issues/3

**Comment by synapticarbors** [comment]
Do you know what the solution is?

**Comment by bollwyvl** [comment]
ehm, does the circle token for GH need to be rejiggered?

I've wondered why this line exists:
```
git config --global url."ssh://git@github.com".insteadOf "https://github.com" || true
```
Seems it would clear up this recurring issue... but would have to dig in more....

**Comment by synapticarbors** [comment]
I'm going to re-add it as per suggestion on gitter

**Pull request merged**
